{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# 训练深度神经网络"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Batch normalization批量标准化"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 40,
   "metadata": {},
   "outputs": [],
   "source": [
    "from utils import (reset_tf_graph, show_tf_graph)\n",
    "import tensorflow as tf\n",
    "import numpy as np"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 41,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 加载mnist数据\n",
    "(X_train, y_train), (X_test, y_test) = tf.keras.datasets.mnist.load_data()\n",
    "X_train = X_train.astype(np.float32).reshape(-1, 28*28) / 255.0\n",
    "X_test = X_test.astype(np.float32).reshape(-1, 28*28) / 255.0\n",
    "y_train = y_train.astype(np.int32)\n",
    "y_test = y_test.astype(np.int32)\n",
    "X_valid, X_train = X_train[:5000], X_train[5000:]\n",
    "y_valid, y_train = y_train[:5000], y_train[5000:]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 42,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82b9e4ca20>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82b9e4ca20>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82b9e4ca20>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82b9e4ca20>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method BatchNormalization.call of <tensorflow.python.layers.normalization.BatchNormalization object at 0x7f82b9e4ca20>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BatchNormalization.call of <tensorflow.python.layers.normalization.BatchNormalization object at 0x7f82b9e4ca20>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method BatchNormalization.call of <tensorflow.python.layers.normalization.BatchNormalization object at 0x7f82b9e4ca20>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BatchNormalization.call of <tensorflow.python.layers.normalization.BatchNormalization object at 0x7f82b9e4ca20>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82b9e4ca20>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82b9e4ca20>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82b9e4ca20>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82b9e4ca20>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method BatchNormalization.call of <tensorflow.python.layers.normalization.BatchNormalization object at 0x7f82b9e4ca20>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BatchNormalization.call of <tensorflow.python.layers.normalization.BatchNormalization object at 0x7f82b9e4ca20>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method BatchNormalization.call of <tensorflow.python.layers.normalization.BatchNormalization object at 0x7f82b9e4ca20>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BatchNormalization.call of <tensorflow.python.layers.normalization.BatchNormalization object at 0x7f82b9e4ca20>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82b9e4ca20>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82b9e4ca20>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82b9e4ca20>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82b9e4ca20>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method BatchNormalization.call of <tensorflow.python.layers.normalization.BatchNormalization object at 0x7f82b9e4ca20>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BatchNormalization.call of <tensorflow.python.layers.normalization.BatchNormalization object at 0x7f82b9e4ca20>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method BatchNormalization.call of <tensorflow.python.layers.normalization.BatchNormalization object at 0x7f82b9e4ca20>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BatchNormalization.call of <tensorflow.python.layers.normalization.BatchNormalization object at 0x7f82b9e4ca20>>: AssertionError: Bad argument number for Name: 3, expecting 4\n"
     ]
    }
   ],
   "source": [
    "from functools import partial\n",
    "\n",
    "reset_tf_graph()\n",
    "\n",
    "n_inputs = 28*28 # minst里的图像分辨率是28*28\n",
    "n_hidden1 = 300 # 第一个隐藏层的神经元数量\n",
    "n_hidden2 = 100\n",
    "n_outputs = 10 # 分类10个数字\n",
    "\n",
    "batch_norm_momentum = 0.9 # 标准化的偏移量\n",
    "\n",
    "learning_rate = 0.01\n",
    "\n",
    "X = tf.placeholder(tf.float32, shape=(None, n_inputs), name=\"X\")\n",
    "y = tf.placeholder(tf.int32, shape=(None), name=\"y\")\n",
    "training = tf.placeholder_with_default(False, shape=(), name='training')\n",
    "\n",
    "with tf.name_scope(\"dnn\"):\n",
    "    he_init = tf.variance_scaling_initializer() # 使用HE初始化权重\n",
    "\n",
    "    my_batch_norm_layer = partial( # 类似做函数的柯里化curring, 填入部分函数值生成新的函数\n",
    "            tf.layers.batch_normalization,\n",
    "            training=training,\n",
    "            momentum=batch_norm_momentum)\n",
    "\n",
    "    my_dense_layer = partial(\n",
    "            tf.layers.dense,\n",
    "            kernel_initializer=he_init)\n",
    "\n",
    "    hidden1 = my_dense_layer(X, n_hidden1, name=\"hidden1\")\n",
    "    bn1 = tf.nn.elu(my_batch_norm_layer(hidden1)) # 标准化后再执行激活函数ELU - 指数线性单元\n",
    "    hidden2 = my_dense_layer(bn1, n_hidden2, name=\"hidden2\")\n",
    "    bn2 = tf.nn.elu(my_batch_norm_layer(hidden2))\n",
    "    logits_before_bn = my_dense_layer(bn2, n_outputs, name=\"outputs\")\n",
    "    logits = my_batch_norm_layer(logits_before_bn)\n",
    "\n",
    "with tf.name_scope(\"loss\"):\n",
    "    xentropy = tf.nn.sparse_softmax_cross_entropy_with_logits(labels=y, logits=logits)\n",
    "    loss = tf.reduce_mean(xentropy, name=\"loss\")\n",
    "\n",
    "with tf.name_scope(\"train\"):\n",
    "    optimizer = tf.train.GradientDescentOptimizer(learning_rate)\n",
    "    training_op = optimizer.minimize(loss)\n",
    "\n",
    "with tf.name_scope(\"eval\"):\n",
    "    correct = tf.nn.in_top_k(logits, y, 1)\n",
    "    accuracy = tf.reduce_mean(tf.cast(correct, tf.float32))\n",
    "    \n",
    "init = tf.global_variables_initializer()\n",
    "saver = tf.train.Saver()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 43,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "0 Validation accuracy: 0.8952\n",
      "1 Validation accuracy: 0.9202\n",
      "2 Validation accuracy: 0.9318\n",
      "3 Validation accuracy: 0.9422\n",
      "4 Validation accuracy: 0.9468\n",
      "5 Validation accuracy: 0.954\n",
      "6 Validation accuracy: 0.9568\n",
      "7 Validation accuracy: 0.96\n",
      "8 Validation accuracy: 0.962\n",
      "9 Validation accuracy: 0.9638\n",
      "10 Validation accuracy: 0.9662\n",
      "11 Validation accuracy: 0.9682\n",
      "12 Validation accuracy: 0.9672\n",
      "13 Validation accuracy: 0.9696\n",
      "14 Validation accuracy: 0.9706\n",
      "15 Validation accuracy: 0.9704\n",
      "16 Validation accuracy: 0.9718\n",
      "17 Validation accuracy: 0.9726\n",
      "18 Validation accuracy: 0.9738\n",
      "19 Validation accuracy: 0.9742\n"
     ]
    }
   ],
   "source": [
    "n_epochs = 20\n",
    "batch_size = 200\n",
    "\n",
    "# 定义一个从训练集中随机挑选50个实例的方法\n",
    "def batch_generator(X, y, size):\n",
    "    rnd_idx = np.random.permutation(len(X)) # len(X)是矩阵X的第0维的长度, 生成0..len(X)的随机数\n",
    "    n_batches = len(X) // batch_size # //是整除, mod\n",
    "    for batch_idx in np.array_split(rnd_idx, n_batches):\n",
    "        X_batch, y_batch = X[batch_idx], y[batch_idx]\n",
    "        yield X_batch, y_batch # yield定义了生成器generator, 可以用next(generator)来调用, 也可以用for循环调用\n",
    "\n",
    "extra_update_ops = tf.get_collection(tf.GraphKeys.UPDATE_OPS)\n",
    "\n",
    "with tf.Session() as sess:\n",
    "    init.run()\n",
    "    for epoch in range(n_epochs):\n",
    "        for X_batch, y_batch in batch_generator(X_train, y_train, batch_size):\n",
    "            sess.run([training_op, extra_update_ops],\n",
    "                     feed_dict={training: True, X: X_batch, y: y_batch})\n",
    "        accuracy_val = accuracy.eval(feed_dict={X: X_valid, y: y_valid})\n",
    "        print(epoch, \"Validation accuracy:\", accuracy_val)\n",
    "\n",
    "    save_path = saver.save(sess, \"./chpt11/my_model_final.ckpt\")\n",
    "    \n",
    "file_writer = tf.summary.FileWriter(\"./chpt11/graph\", tf.get_default_graph())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 44,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "['hidden1/kernel:0',\n",
       " 'hidden1/bias:0',\n",
       " 'batch_normalization/gamma:0',\n",
       " 'batch_normalization/beta:0',\n",
       " 'batch_normalization/moving_mean:0',\n",
       " 'batch_normalization/moving_variance:0',\n",
       " 'hidden2/kernel:0',\n",
       " 'hidden2/bias:0',\n",
       " 'batch_normalization_1/gamma:0',\n",
       " 'batch_normalization_1/beta:0',\n",
       " 'batch_normalization_1/moving_mean:0',\n",
       " 'batch_normalization_1/moving_variance:0',\n",
       " 'outputs/kernel:0',\n",
       " 'outputs/bias:0',\n",
       " 'batch_normalization_2/gamma:0',\n",
       " 'batch_normalization_2/beta:0',\n",
       " 'batch_normalization_2/moving_mean:0',\n",
       " 'batch_normalization_2/moving_variance:0']"
      ]
     },
     "execution_count": 44,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "[v.name for v in tf.global_variables()]"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## MAX Norm 最大范数约束正则化"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 45,
   "metadata": {},
   "outputs": [],
   "source": [
    "from utils import (reset_tf_graph, show_tf_graph)\n",
    "import tensorflow as tf\n",
    "import numpy as np\n",
    "\n",
    "# 加载mnist数据\n",
    "(X_train, y_train), (X_test, y_test) = tf.keras.datasets.mnist.load_data()\n",
    "X_train = X_train.astype(np.float32).reshape(-1, 28*28) / 255.0\n",
    "X_test = X_test.astype(np.float32).reshape(-1, 28*28) / 255.0\n",
    "y_train = y_train.astype(np.int32)\n",
    "y_test = y_test.astype(np.int32)\n",
    "X_valid, X_train = X_train[:5000], X_train[5000:]\n",
    "y_valid, y_train = y_train[:5000], y_train[5000:]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 46,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:From /home/living/anaconda3/envs/dev-gpu/lib/python3.7/site-packages/tensorflow/python/ops/init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Call initializer instance with the dtype argument instead of passing it to the constructor\n",
      "WARNING:tensorflow:From /home/living/anaconda3/envs/dev-gpu/lib/python3.7/site-packages/tensorflow/python/ops/clip_ops.py:157: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Use tf.where in 2.0, which has the same broadcast rule as np.where\n",
      "WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82b9342e48>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82b9342e48>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82b9342e48>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82b9342e48>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82b9342e48>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82b9342e48>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82b9342e48>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82b9342e48>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82b9342e48>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82b9342e48>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82b9342e48>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82b9342e48>>: AssertionError: Bad argument number for Name: 3, expecting 4\n"
     ]
    }
   ],
   "source": [
    "reset_tf_graph()\n",
    "\n",
    "n_inputs = 28 * 28\n",
    "n_hidden1 = 300\n",
    "n_hidden2 = 50\n",
    "n_outputs = 10\n",
    "\n",
    "learning_rate = 0.01\n",
    "momentum = 0.9\n",
    "\n",
    "X = tf.placeholder(tf.float32, shape=(None, n_inputs), name=\"X\")\n",
    "y = tf.placeholder(tf.int32, shape=(None), name=\"y\")\n",
    "\n",
    "def max_norm_regularizer(threshold, axes=1, name=\"max_norm\",\n",
    "                         collection=\"max_norm\"):\n",
    "    def max_norm(weights):\n",
    "        clipped = tf.clip_by_norm(weights, clip_norm=threshold, axes=axes)\n",
    "        clip_weights = tf.assign(weights, clipped, name=name)\n",
    "        tf.add_to_collection(collection, clip_weights)\n",
    "        return None # there is no regularization loss term\n",
    "    return max_norm\n",
    "\n",
    "max_norm_reg = max_norm_regularizer(threshold=1.0)\n",
    "\n",
    "with tf.name_scope(\"dnn\"):\n",
    "    hidden1 = tf.layers.dense(X, n_hidden1, activation=tf.nn.relu, name=\"hidden1\", kernel_regularizer=max_norm_reg)\n",
    "    hidden2 = tf.layers.dense(hidden1, n_hidden2, activation=tf.nn.relu, name=\"hidden2\", kernel_regularizer=max_norm_reg)\n",
    "    logits = tf.layers.dense(hidden2, n_outputs, name=\"outputs\")\n",
    "\n",
    "with tf.name_scope(\"loss\"):\n",
    "    xentropy = tf.nn.sparse_softmax_cross_entropy_with_logits(labels=y, logits=logits)\n",
    "    loss = tf.reduce_mean(xentropy, name=\"loss\")\n",
    "\n",
    "with tf.name_scope(\"train\"):\n",
    "    optimizer = tf.train.MomentumOptimizer(learning_rate, momentum)\n",
    "    training_op = optimizer.minimize(loss)    \n",
    "\n",
    "with tf.name_scope(\"eval\"):\n",
    "    correct = tf.nn.in_top_k(logits, y, 1)\n",
    "    accuracy = tf.reduce_mean(tf.cast(correct, tf.float32))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 47,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 定义权重裁剪操作\n",
    "\n",
    "threshold = 1.0\n",
    "weights = tf.get_default_graph().get_tensor_by_name(\"hidden1/kernel:0\")\n",
    "clipped_weights = tf.clip_by_norm(weights, clip_norm=threshold, axes=1)\n",
    "clip_weights = tf.assign(weights, clipped_weights)\n",
    "\n",
    "weights2 = tf.get_default_graph().get_tensor_by_name(\"hidden2/kernel:0\")\n",
    "clipped_weights2 = tf.clip_by_norm(weights2, clip_norm=threshold, axes=1)\n",
    "clip_weights2 = tf.assign(weights2, clipped_weights2)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 48,
   "metadata": {},
   "outputs": [],
   "source": [
    "init = tf.global_variables_initializer()\n",
    "saver = tf.train.Saver()\n",
    "\n",
    "n_epochs = 20\n",
    "batch_size = 50"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 49,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "0 Validation accuracy: 0.9558\n",
      "1 Validation accuracy: 0.9704\n",
      "2 Validation accuracy: 0.9724\n",
      "3 Validation accuracy: 0.9758\n",
      "4 Validation accuracy: 0.9766\n",
      "5 Validation accuracy: 0.9786\n",
      "6 Validation accuracy: 0.9808\n",
      "7 Validation accuracy: 0.9808\n",
      "8 Validation accuracy: 0.98\n",
      "9 Validation accuracy: 0.9802\n",
      "10 Validation accuracy: 0.9822\n",
      "11 Validation accuracy: 0.982\n",
      "12 Validation accuracy: 0.9798\n",
      "13 Validation accuracy: 0.981\n",
      "14 Validation accuracy: 0.9818\n",
      "15 Validation accuracy: 0.9824\n",
      "16 Validation accuracy: 0.9818\n",
      "17 Validation accuracy: 0.9828\n",
      "18 Validation accuracy: 0.9822\n",
      "19 Validation accuracy: 0.9818\n"
     ]
    }
   ],
   "source": [
    "# 定义一个从训练集中随机挑选50个实例的方法\n",
    "def batch_generator(X, y, size):\n",
    "    rnd_idx = np.random.permutation(len(X)) # len(X)是矩阵X的第0维的长度, 生成0..len(X)的随机数\n",
    "    n_batches = len(X) // batch_size # //是整除, mod\n",
    "    for batch_idx in np.array_split(rnd_idx, n_batches):\n",
    "        X_batch, y_batch = X[batch_idx], y[batch_idx]\n",
    "        yield X_batch, y_batch # yield定义了生成器generator, 可以用next(generator)来调用, 也可以用for循环调用\n",
    "\n",
    "with tf.Session() as sess:                                              \n",
    "    init.run()                                                          \n",
    "    for epoch in range(n_epochs):                                       \n",
    "        for X_batch, y_batch in batch_generator(X_train, y_train, batch_size): \n",
    "            sess.run(training_op, feed_dict={X: X_batch, y: y_batch})\n",
    "            clip_weights.eval()\n",
    "            clip_weights2.eval()                                        \n",
    "        acc_valid = accuracy.eval(feed_dict={X: X_valid, y: y_valid})   \n",
    "        print(epoch, \"Validation accuracy:\", acc_valid)                 \n",
    "\n",
    "    save_path = saver.save(sess, \"./chpt11/model/max_norm.ckpt\")\n",
    "    \n",
    "file_writer = tf.summary.FileWriter(\"./chpt11/graph/max_norm\", tf.get_default_graph())"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 习题"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### 8.深度学习。\n",
    "\n",
    "i.  建立一个 DNN,有五个隐藏层,每层 100 个神经元,使用 He 初始化和 ELU 激活函数。\n",
    "\n",
    "ii.  使用 Adam 优化和提前停止,请尝试在 MNIST 上进行训练,但只能使用数字 0 到4,因为我们将在下一个练习中在数字 5 到 9 上进行迁移学习。 您需要一个包含五个神经元的 softmax 输出层,并且一如既往地确保定期保存检查点,并保存最终模型,以便稍后再使用它。\n",
    "\n",
    "iii.  使用交叉验证调整超参数,并查看你能达到什么准确度。\n",
    "\n",
    "iv.  现在尝试添加批量标准化并比较学习曲线:它是否比以前收敛得更快? 它是否会产生更好的模型? v.  模型是否过拟合训练集? 尝试将 dropout 添加到每一层,然后重试。 它有帮助吗?"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 50,
   "metadata": {},
   "outputs": [],
   "source": [
    "from utils import (reset_tf_graph, show_tf_graph)\n",
    "import tensorflow as tf\n",
    "import numpy as np\n",
    "from functools import partial\n",
    "import matplotlib.pyplot as plt"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 51,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 加载mnist数据\n",
    "(X_train, y_train), (X_test, y_test) = tf.keras.datasets.mnist.load_data()\n",
    "X_train = X_train.astype(np.float32).reshape(-1, 28*28) / 255.0\n",
    "X_test = X_test.astype(np.float32).reshape(-1, 28*28) / 255.0\n",
    "y_train = y_train.astype(np.int32)\n",
    "y_test = y_test.astype(np.int32)\n",
    "X_valid, X_train = X_train[:5000], X_train[5000:]\n",
    "y_valid, y_train = y_train[:5000], y_train[5000:]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 52,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 取数据集中0~4的部分\n",
    "X_train_04 = X_train[y_train <= 4]\n",
    "y_train_04 = y_train[y_train <= 4]\n",
    "X_valid_04 = X_valid[y_valid <= 4]\n",
    "y_valid_04 = y_valid[y_valid <= 4]\n",
    "X_test_04 = X_test[y_test <= 4]\n",
    "y_test_04 = y_test[y_test <= 4]"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "#### 开始构建模型"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 53,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82b6992438>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82b6992438>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82b6992438>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82b6992438>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82b6c16358>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82b6c16358>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82b6c16358>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82b6c16358>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82b69d0a90>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82b69d0a90>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82b69d0a90>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82b69d0a90>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82b9342780>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82b9342780>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82b9342780>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82b9342780>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82b69d0a58>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82b69d0a58>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82b69d0a58>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82b69d0a58>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82b9e4c6a0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82b9e4c6a0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82b9e4c6a0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82b9e4c6a0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n"
     ]
    }
   ],
   "source": [
    "n_inputs = 28*28\n",
    "n_outputs = 5\n",
    "n_hidden_neurons = 100\n",
    "n_hidden_layers = 5\n",
    "\n",
    "reset_tf_graph()\n",
    "\n",
    "# 定义输入参数\n",
    "X = tf.placeholder(tf.float32, shape=(None, n_inputs), name=\"X\")\n",
    "y = tf.placeholder(tf.int32, shape=(None), name=\"y\")\n",
    "\n",
    "# 定义层\n",
    "he_init = tf.initializers.variance_scaling()\n",
    "\n",
    "def make_dnn(inputs):\n",
    "    with tf.name_scope(\"dnn\") as scope:\n",
    "        for n in range(n_hidden_layers):\n",
    "            inputs = tf.layers.dense(inputs, n_hidden_neurons, \n",
    "                                     activation=tf.nn.elu, kernel_initializer=he_init,\n",
    "                                     name=\"hidden%d\" % (n + 1))\n",
    "        return inputs\n",
    "\n",
    "dnn_outputs = make_dnn(X)\n",
    "logits = tf.layers.dense(dnn_outputs, n_outputs, \n",
    "                         kernel_initializer=he_init,\n",
    "                        name=\"logits\")\n",
    "y_probs = tf.nn.softmax(logits, name=\"y_probs\")\n",
    "\n",
    "# 定义交叉熵损失函数\n",
    "with tf.name_scope(\"loss\"):\n",
    "    xentropy = tf.nn.sparse_softmax_cross_entropy_with_logits(labels=y, logits=logits)\n",
    "    loss = tf.reduce_mean(xentropy, name=\"loss\")\n",
    "\n",
    "# 定义训练操作\n",
    "learning_rate = 0.01\n",
    "with tf.name_scope(\"train\"):\n",
    "    optimizer = tf.train.AdamOptimizer(learning_rate)\n",
    "    training_op = optimizer.minimize(loss)\n",
    "\n",
    "with tf.name_scope(\"eval\"):\n",
    "    correct = tf.nn.in_top_k(logits, y, 1)\n",
    "    accuracy = tf.reduce_mean(tf.cast(correct, tf.float32))"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "#### 开始训练"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 54,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "0 loss:  0.13895851\n",
      "0 Validation accuracy: 0.9679437\n",
      "epoch: 0, validation loss: 0.138959, best loss: 0.138959, accuracy: 96.79%\n",
      "1 loss:  0.5139847\n",
      "1 Validation accuracy: 0.90539485\n",
      "epoch: 1, validation loss: 0.513985, best loss: 0.138959, accuracy: 90.54%\n",
      "2 loss:  0.17396334\n",
      "2 Validation accuracy: 0.96638\n",
      "epoch: 2, validation loss: 0.173963, best loss: 0.138959, accuracy: 96.64%\n",
      "3 loss:  0.187747\n",
      "3 Validation accuracy: 0.9652072\n",
      "epoch: 3, validation loss: 0.187747, best loss: 0.138959, accuracy: 96.52%\n",
      "4 loss:  0.14861722\n",
      "4 Validation accuracy: 0.971853\n",
      "epoch: 4, validation loss: 0.148617, best loss: 0.138959, accuracy: 97.19%\n",
      "5 loss:  0.32130894\n",
      "5 Validation accuracy: 0.9460516\n",
      "epoch: 5, validation loss: 0.321309, best loss: 0.138959, accuracy: 94.61%\n",
      "6 loss:  0.13058099\n",
      "6 Validation accuracy: 0.971853\n",
      "epoch: 6, validation loss: 0.130581, best loss: 0.130581, accuracy: 97.19%\n",
      "7 loss:  0.4025895\n",
      "7 Validation accuracy: 0.9089132\n",
      "epoch: 7, validation loss: 0.402589, best loss: 0.130581, accuracy: 90.89%\n",
      "8 loss:  0.17270242\n",
      "8 Validation accuracy: 0.9741986\n",
      "epoch: 8, validation loss: 0.172702, best loss: 0.130581, accuracy: 97.42%\n",
      "9 loss:  0.101213135\n",
      "9 Validation accuracy: 0.98358095\n",
      "epoch: 9, validation loss: 0.101213, best loss: 0.101213, accuracy: 98.36%\n",
      "10 loss:  0.28335792\n",
      "10 Validation accuracy: 0.9616888\n",
      "epoch: 10, validation loss: 0.283358, best loss: 0.101213, accuracy: 96.17%\n",
      "11 loss:  0.16316651\n",
      "11 Validation accuracy: 0.9741986\n",
      "epoch: 11, validation loss: 0.163167, best loss: 0.101213, accuracy: 97.42%\n",
      "12 loss:  0.2199651\n",
      "12 Validation accuracy: 0.9628616\n",
      "epoch: 12, validation loss: 0.219965, best loss: 0.101213, accuracy: 96.29%\n",
      "13 loss:  0.34530494\n",
      "13 Validation accuracy: 0.9241595\n",
      "epoch: 13, validation loss: 0.345305, best loss: 0.101213, accuracy: 92.42%\n",
      "14 loss:  0.23631316\n",
      "14 Validation accuracy: 0.9804535\n",
      "epoch: 14, validation loss: 0.236313, best loss: 0.101213, accuracy: 98.05%\n",
      "15 loss:  0.22269791\n",
      "15 Validation accuracy: 0.97615325\n",
      "epoch: 15, validation loss: 0.222698, best loss: 0.101213, accuracy: 97.62%\n",
      "16 loss:  0.14717107\n",
      "16 Validation accuracy: 0.9816263\n",
      "epoch: 16, validation loss: 0.147171, best loss: 0.101213, accuracy: 98.16%\n",
      "17 loss:  1.0686076\n",
      "17 Validation accuracy: 0.393276\n",
      "epoch: 17, validation loss: 1.068608, best loss: 0.101213, accuracy: 39.33%\n",
      "18 loss:  1.0173422\n",
      "18 Validation accuracy: 0.39796716\n",
      "epoch: 18, validation loss: 1.017342, best loss: 0.101213, accuracy: 39.80%\n",
      "19 loss:  0.9963604\n",
      "19 Validation accuracy: 0.40578577\n",
      "epoch: 19, validation loss: 0.996360, best loss: 0.101213, accuracy: 40.58%\n",
      "20 loss:  1.1217464\n",
      "20 Validation accuracy: 0.39562157\n",
      "epoch: 20, validation loss: 1.121746, best loss: 0.101213, accuracy: 39.56%\n",
      "21 loss:  1.0152369\n",
      "21 Validation accuracy: 0.40930414\n",
      "epoch: 21, validation loss: 1.015237, best loss: 0.101213, accuracy: 40.93%\n",
      "22 loss:  0.98226064\n",
      "22 Validation accuracy: 0.40539485\n",
      "epoch: 22, validation loss: 0.982261, best loss: 0.101213, accuracy: 40.54%\n",
      "23 loss:  1.0608273\n",
      "23 Validation accuracy: 0.4073495\n",
      "epoch: 23, validation loss: 1.060827, best loss: 0.101213, accuracy: 40.73%\n",
      "24 loss:  1.0484282\n",
      "24 Validation accuracy: 0.39132133\n",
      "epoch: 24, validation loss: 1.048428, best loss: 0.101213, accuracy: 39.13%\n",
      "25 loss:  1.0864471\n",
      "25 Validation accuracy: 0.3983581\n",
      "epoch: 25, validation loss: 1.086447, best loss: 0.101213, accuracy: 39.84%\n",
      "26 loss:  1.0250312\n",
      "26 Validation accuracy: 0.4026583\n",
      "epoch: 26, validation loss: 1.025031, best loss: 0.101213, accuracy: 40.27%\n",
      "27 loss:  1.0516782\n",
      "27 Validation accuracy: 0.40813136\n",
      "epoch: 27, validation loss: 1.051678, best loss: 0.101213, accuracy: 40.81%\n",
      "28 loss:  1.0690209\n",
      "28 Validation accuracy: 0.404613\n",
      "epoch: 28, validation loss: 1.069021, best loss: 0.101213, accuracy: 40.46%\n",
      "29 loss:  1.0187942\n",
      "29 Validation accuracy: 0.4061767\n",
      "epoch: 29, validation loss: 1.018794, best loss: 0.101213, accuracy: 40.62%\n",
      "30 loss:  1.0595031\n",
      "30 Validation accuracy: 0.40344018\n",
      "Early stopping! \n",
      "INFO:tensorflow:Restoring parameters from ./chpt11/model/ex8_2.ckpt\n",
      "Final test accuracy: 98.64%\n"
     ]
    }
   ],
   "source": [
    "n_epochs = 1000\n",
    "batch_size = 20\n",
    "n_epochs_before_stop = 20\n",
    "\n",
    "init = tf.global_variables_initializer()\n",
    "saver = tf.train.Saver()\n",
    "\n",
    "best_loss = np.infty\n",
    "\n",
    "\n",
    "# 定义一个从训练集中随机挑选50个实例的方法\n",
    "def batch_generator(X, y, size):\n",
    "    rnd_idx = np.random.permutation(len(X)) # len(X)是矩阵X的第0维的长度, 生成0..len(X)的随机数\n",
    "    n_batches = len(X) // batch_size # //是整除, mod\n",
    "    for batch_idx in np.array_split(rnd_idx, n_batches):\n",
    "        X_batch, y_batch = X[batch_idx], y[batch_idx]\n",
    "        yield X_batch, y_batch # yield定义了生成器generator, 可以用next(generator)来调用, 也可以用for循环调用\n",
    "        \n",
    "with tf.Session() as sess:\n",
    "    init.run()\n",
    "    n_epochs_after_best = 0\n",
    "    for epoch in range(n_epochs):\n",
    "        for X_batch, y_batch in batch_generator(X_train_04, y_train_04, batch_size):\n",
    "            sess.run(training_op, feed_dict={X: X_batch, y: y_batch})\n",
    "        \n",
    "        the_loss, acc_valid = sess.run([loss, accuracy], feed_dict={X: X_valid_04, y: y_valid_04})\n",
    "        print(epoch, \"loss: \", the_loss)\n",
    "        print(epoch, \"Validation accuracy:\", acc_valid)\n",
    "        \n",
    "        if the_loss < best_loss:\n",
    "            best_loss = the_loss\n",
    "            n_epochs_after_best = 0\n",
    "            save_path = saver.save(sess, \"./chpt11/model/ex8_2.ckpt\")\n",
    "        else:\n",
    "            n_epochs_after_best += 1\n",
    "            if n_epochs_after_best > n_epochs_before_stop:\n",
    "                print(\"Early stopping! \")\n",
    "                break\n",
    "        print(\"epoch: {}, validation loss: {:.6f}, best loss: {:.6f}, accuracy: {:.2f}%\".format(\n",
    "            epoch, the_loss, best_loss, acc_valid * 100))\n",
    "    \n",
    "with tf.Session() as sess:\n",
    "    saver.restore(sess, \"./chpt11/model/ex8_2.ckpt\")\n",
    "    acc_test = accuracy.eval(feed_dict={X: X_test_04, y: y_test_04})\n",
    "    print(\"Final test accuracy: {:.2f}%\".format(acc_test * 100))"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "#### 使用批量标准化重新定义模型"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 55,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82b5e80d30>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82b5e80d30>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82b5e80d30>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82b5e80d30>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method BatchNormalization.call of <tensorflow.python.layers.normalization.BatchNormalization object at 0x7f82b9342a90>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BatchNormalization.call of <tensorflow.python.layers.normalization.BatchNormalization object at 0x7f82b9342a90>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method BatchNormalization.call of <tensorflow.python.layers.normalization.BatchNormalization object at 0x7f82b9342a90>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BatchNormalization.call of <tensorflow.python.layers.normalization.BatchNormalization object at 0x7f82b9342a90>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82b9342550>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82b9342550>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82b9342550>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82b9342550>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method BatchNormalization.call of <tensorflow.python.layers.normalization.BatchNormalization object at 0x7f82c19112b0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BatchNormalization.call of <tensorflow.python.layers.normalization.BatchNormalization object at 0x7f82c19112b0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method BatchNormalization.call of <tensorflow.python.layers.normalization.BatchNormalization object at 0x7f82c19112b0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BatchNormalization.call of <tensorflow.python.layers.normalization.BatchNormalization object at 0x7f82c19112b0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82b9e32588>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82b9e32588>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82b9e32588>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82b9e32588>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method BatchNormalization.call of <tensorflow.python.layers.normalization.BatchNormalization object at 0x7f82b9e32588>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BatchNormalization.call of <tensorflow.python.layers.normalization.BatchNormalization object at 0x7f82b9e32588>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method BatchNormalization.call of <tensorflow.python.layers.normalization.BatchNormalization object at 0x7f82b9e32588>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BatchNormalization.call of <tensorflow.python.layers.normalization.BatchNormalization object at 0x7f82b9e32588>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82ba0714e0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82ba0714e0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82ba0714e0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82ba0714e0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method BatchNormalization.call of <tensorflow.python.layers.normalization.BatchNormalization object at 0x7f82ba0714e0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BatchNormalization.call of <tensorflow.python.layers.normalization.BatchNormalization object at 0x7f82ba0714e0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method BatchNormalization.call of <tensorflow.python.layers.normalization.BatchNormalization object at 0x7f82ba0714e0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BatchNormalization.call of <tensorflow.python.layers.normalization.BatchNormalization object at 0x7f82ba0714e0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82bcbb96a0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82bcbb96a0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82bcbb96a0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82bcbb96a0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method BatchNormalization.call of <tensorflow.python.layers.normalization.BatchNormalization object at 0x7f82bcbb96a0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BatchNormalization.call of <tensorflow.python.layers.normalization.BatchNormalization object at 0x7f82bcbb96a0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method BatchNormalization.call of <tensorflow.python.layers.normalization.BatchNormalization object at 0x7f82bcbb96a0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BatchNormalization.call of <tensorflow.python.layers.normalization.BatchNormalization object at 0x7f82bcbb96a0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82b69924e0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82b69924e0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82b69924e0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82b69924e0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n"
     ]
    }
   ],
   "source": [
    "n_inputs = 28*28\n",
    "n_outputs = 5\n",
    "n_hidden_neurons = 100\n",
    "n_hidden_layers = 5\n",
    "\n",
    "reset_tf_graph()\n",
    "\n",
    "# 定义输入参数\n",
    "X = tf.placeholder(tf.float32, shape=(None, n_inputs), name=\"X\")\n",
    "y = tf.placeholder(tf.int32, shape=(None), name=\"y\")\n",
    "training = tf.placeholder(tf.bool, name=\"training\")\n",
    "\n",
    "# 定义层\n",
    "he_init = tf.initializers.variance_scaling()\n",
    "\n",
    "def make_dnn(inputs):\n",
    "    with tf.name_scope(\"dnn\") as scope:\n",
    "        for n in range(n_hidden_layers):\n",
    "            inputs = tf.layers.dense(inputs, n_hidden_neurons, \n",
    "                                     kernel_initializer=he_init,\n",
    "                                     name=\"hidden%d\" % (n + 1))\n",
    "            # 添加批量标准化\n",
    "            inputs = tf.nn.elu(tf.layers.batch_normalization(inputs, training=training, momentum=0.9))\n",
    "        return inputs\n",
    "\n",
    "dnn_outputs = make_dnn(X)\n",
    "logits = tf.layers.dense(dnn_outputs, n_outputs, \n",
    "                         kernel_initializer=he_init,\n",
    "                        name=\"logits\")\n",
    "y_probs = tf.nn.softmax(logits, name=\"y_probs\")\n",
    "\n",
    "# 定义交叉熵损失函数\n",
    "with tf.name_scope(\"loss\"):\n",
    "    xentropy = tf.nn.sparse_softmax_cross_entropy_with_logits(labels=y, logits=logits)\n",
    "    loss = tf.reduce_mean(xentropy, name=\"loss\")\n",
    "\n",
    "# 定义训练操作\n",
    "learning_rate = 0.01\n",
    "with tf.name_scope(\"train\"):\n",
    "    optimizer = tf.train.AdamOptimizer(learning_rate)\n",
    "    training_op = optimizer.minimize(loss)\n",
    "\n",
    "with tf.name_scope(\"eval\"):\n",
    "    correct = tf.nn.in_top_k(logits, y, 1)\n",
    "    accuracy = tf.reduce_mean(tf.cast(correct, tf.float32))"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "#### 开始训练"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 56,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "0 loss:  0.075847685\n",
      "0 Validation accuracy: 0.97732604\n",
      "epoch: 0, validation loss: 0.075848, best loss: 0.075848, accuracy: 97.73%\n",
      "1 loss:  0.059287645\n",
      "1 Validation accuracy: 0.9812353\n",
      "epoch: 1, validation loss: 0.059288, best loss: 0.059288, accuracy: 98.12%\n",
      "2 loss:  0.079713866\n",
      "2 Validation accuracy: 0.97732604\n",
      "epoch: 2, validation loss: 0.079714, best loss: 0.059288, accuracy: 97.73%\n",
      "3 loss:  0.053197168\n",
      "3 Validation accuracy: 0.98553556\n",
      "epoch: 3, validation loss: 0.053197, best loss: 0.053197, accuracy: 98.55%\n",
      "4 loss:  0.045146145\n",
      "4 Validation accuracy: 0.9859265\n",
      "epoch: 4, validation loss: 0.045146, best loss: 0.045146, accuracy: 98.59%\n",
      "5 loss:  0.037373\n",
      "5 Validation accuracy: 0.98944485\n",
      "epoch: 5, validation loss: 0.037373, best loss: 0.037373, accuracy: 98.94%\n",
      "6 loss:  0.037881285\n",
      "6 Validation accuracy: 0.9870993\n",
      "epoch: 6, validation loss: 0.037881, best loss: 0.037373, accuracy: 98.71%\n",
      "7 loss:  0.029262692\n",
      "7 Validation accuracy: 0.9910086\n",
      "epoch: 7, validation loss: 0.029263, best loss: 0.029263, accuracy: 99.10%\n",
      "8 loss:  0.036447674\n",
      "8 Validation accuracy: 0.9898358\n",
      "epoch: 8, validation loss: 0.036448, best loss: 0.029263, accuracy: 98.98%\n",
      "9 loss:  0.03172217\n",
      "9 Validation accuracy: 0.9906177\n",
      "epoch: 9, validation loss: 0.031722, best loss: 0.029263, accuracy: 99.06%\n",
      "10 loss:  0.038287256\n",
      "10 Validation accuracy: 0.98944485\n",
      "epoch: 10, validation loss: 0.038287, best loss: 0.029263, accuracy: 98.94%\n",
      "11 loss:  0.047146957\n",
      "11 Validation accuracy: 0.98944485\n",
      "epoch: 11, validation loss: 0.047147, best loss: 0.029263, accuracy: 98.94%\n",
      "12 loss:  0.059113324\n",
      "12 Validation accuracy: 0.98397183\n",
      "epoch: 12, validation loss: 0.059113, best loss: 0.029263, accuracy: 98.40%\n",
      "13 loss:  0.047077935\n",
      "13 Validation accuracy: 0.98749024\n",
      "epoch: 13, validation loss: 0.047078, best loss: 0.029263, accuracy: 98.75%\n",
      "14 loss:  0.038700428\n",
      "14 Validation accuracy: 0.9906177\n",
      "epoch: 14, validation loss: 0.038700, best loss: 0.029263, accuracy: 99.06%\n",
      "15 loss:  0.037548903\n",
      "15 Validation accuracy: 0.98944485\n",
      "epoch: 15, validation loss: 0.037549, best loss: 0.029263, accuracy: 98.94%\n",
      "16 loss:  0.039441384\n",
      "16 Validation accuracy: 0.99022675\n",
      "epoch: 16, validation loss: 0.039441, best loss: 0.029263, accuracy: 99.02%\n",
      "17 loss:  0.04223466\n",
      "17 Validation accuracy: 0.9898358\n",
      "epoch: 17, validation loss: 0.042235, best loss: 0.029263, accuracy: 98.98%\n",
      "18 loss:  0.050480407\n",
      "18 Validation accuracy: 0.98905396\n",
      "epoch: 18, validation loss: 0.050480, best loss: 0.029263, accuracy: 98.91%\n",
      "19 loss:  0.038975496\n",
      "19 Validation accuracy: 0.9913995\n",
      "epoch: 19, validation loss: 0.038975, best loss: 0.029263, accuracy: 99.14%\n",
      "20 loss:  0.036071565\n",
      "20 Validation accuracy: 0.9913995\n",
      "epoch: 20, validation loss: 0.036072, best loss: 0.029263, accuracy: 99.14%\n",
      "21 loss:  0.036763974\n",
      "21 Validation accuracy: 0.9898358\n",
      "epoch: 21, validation loss: 0.036764, best loss: 0.029263, accuracy: 98.98%\n",
      "22 loss:  0.038013574\n",
      "22 Validation accuracy: 0.9898358\n",
      "epoch: 22, validation loss: 0.038014, best loss: 0.029263, accuracy: 98.98%\n",
      "23 loss:  0.041261006\n",
      "23 Validation accuracy: 0.99022675\n",
      "epoch: 23, validation loss: 0.041261, best loss: 0.029263, accuracy: 99.02%\n",
      "24 loss:  0.035017096\n",
      "24 Validation accuracy: 0.99296325\n",
      "epoch: 24, validation loss: 0.035017, best loss: 0.029263, accuracy: 99.30%\n",
      "25 loss:  0.043448303\n",
      "25 Validation accuracy: 0.9917905\n",
      "epoch: 25, validation loss: 0.043448, best loss: 0.029263, accuracy: 99.18%\n",
      "26 loss:  0.035885397\n",
      "26 Validation accuracy: 0.9913995\n",
      "epoch: 26, validation loss: 0.035885, best loss: 0.029263, accuracy: 99.14%\n",
      "27 loss:  0.045594428\n",
      "27 Validation accuracy: 0.9882721\n",
      "epoch: 27, validation loss: 0.045594, best loss: 0.029263, accuracy: 98.83%\n",
      "28 loss:  0.037924636\n",
      "28 Validation accuracy: 0.9906177\n",
      "Early stopping! \n",
      "INFO:tensorflow:Restoring parameters from ./chpt11/model/ex8_4.ckpt\n",
      "Final test accuracy: 99.30%\n"
     ]
    }
   ],
   "source": [
    "n_epochs = 1000\n",
    "batch_size = 20\n",
    "n_epochs_before_stop = 20\n",
    "\n",
    "init = tf.global_variables_initializer()\n",
    "saver = tf.train.Saver()\n",
    "\n",
    "best_loss = np.infty\n",
    "\n",
    "\n",
    "# 定义一个从训练集中随机挑选50个实例的方法\n",
    "def batch_generator(X, y, size):\n",
    "    rnd_idx = np.random.permutation(len(X)) # len(X)是矩阵X的第0维的长度, 生成0..len(X)的随机数\n",
    "    n_batches = len(X) // batch_size # //是整除, mod\n",
    "    for batch_idx in np.array_split(rnd_idx, n_batches):\n",
    "        X_batch, y_batch = X[batch_idx], y[batch_idx]\n",
    "        yield X_batch, y_batch # yield定义了生成器generator, 可以用next(generator)来调用, 也可以用for循环调用\n",
    "        \n",
    "with tf.Session() as sess:\n",
    "    init.run()\n",
    "    n_epochs_after_best = 0\n",
    "    for epoch in range(n_epochs):\n",
    "        for X_batch, y_batch in batch_generator(X_train_04, y_train_04, batch_size):\n",
    "            sess.run(training_op, feed_dict={X: X_batch, y: y_batch, training: True})\n",
    "        \n",
    "        the_loss, acc_valid = sess.run([loss, accuracy], feed_dict={X: X_valid_04, y: y_valid_04, training: True})\n",
    "        print(epoch, \"loss: \", the_loss)\n",
    "        print(epoch, \"Validation accuracy:\", acc_valid)\n",
    "        \n",
    "        if the_loss < best_loss:\n",
    "            best_loss = the_loss\n",
    "            n_epochs_after_best = 0\n",
    "            save_path = saver.save(sess, \"./chpt11/model/ex8_4.ckpt\")\n",
    "        else:\n",
    "            n_epochs_after_best += 1\n",
    "            if n_epochs_after_best > n_epochs_before_stop:\n",
    "                print(\"Early stopping! \")\n",
    "                break\n",
    "        print(\"epoch: {}, validation loss: {:.6f}, best loss: {:.6f}, accuracy: {:.2f}%\".format(\n",
    "            epoch, the_loss, best_loss, acc_valid * 100))\n",
    "    \n",
    "with tf.Session() as sess:\n",
    "    saver.restore(sess, \"./chpt11/model/ex8_4.ckpt\")\n",
    "    acc_test = accuracy.eval(feed_dict={X: X_test_04, y: y_test_04, training: True})\n",
    "    print(\"Final test accuracy: {:.2f}%\".format(acc_test * 100))"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "#### 是否过拟合训练数据?"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 57,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "INFO:tensorflow:Restoring parameters from ./chpt11/model/ex8_4.ckpt\n",
      "accuracy on traning set: 99.66%\n"
     ]
    }
   ],
   "source": [
    "with tf.Session() as sess:\n",
    "    saver.restore(sess, \"./chpt11/model/ex8_4.ckpt\")\n",
    "    acc_train = accuracy.eval(feed_dict={X: X_train_04, y: y_train_04, training: True})\n",
    "    print(\"accuracy on traning set: {:.2f}%\".format(acc_train * 100))"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "#### 使用dropout"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 60,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:Entity <bound method Dropout.call of <tensorflow.python.layers.core.Dropout object at 0x7f82aec3b3c8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dropout.call of <tensorflow.python.layers.core.Dropout object at 0x7f82aec3b3c8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dropout.call of <tensorflow.python.layers.core.Dropout object at 0x7f82aec3b3c8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dropout.call of <tensorflow.python.layers.core.Dropout object at 0x7f82aec3b3c8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82b9ee0a20>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82b9ee0a20>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82b9ee0a20>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82b9ee0a20>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method BatchNormalization.call of <tensorflow.python.layers.normalization.BatchNormalization object at 0x7f82b4ba0748>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BatchNormalization.call of <tensorflow.python.layers.normalization.BatchNormalization object at 0x7f82b4ba0748>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method BatchNormalization.call of <tensorflow.python.layers.normalization.BatchNormalization object at 0x7f82b4ba0748>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BatchNormalization.call of <tensorflow.python.layers.normalization.BatchNormalization object at 0x7f82b4ba0748>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Dropout.call of <tensorflow.python.layers.core.Dropout object at 0x7f82b4ba0748>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dropout.call of <tensorflow.python.layers.core.Dropout object at 0x7f82b4ba0748>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dropout.call of <tensorflow.python.layers.core.Dropout object at 0x7f82b4ba0748>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dropout.call of <tensorflow.python.layers.core.Dropout object at 0x7f82b4ba0748>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82c30ac208>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82c30ac208>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82c30ac208>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82c30ac208>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method BatchNormalization.call of <tensorflow.python.layers.normalization.BatchNormalization object at 0x7f82c30ac208>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BatchNormalization.call of <tensorflow.python.layers.normalization.BatchNormalization object at 0x7f82c30ac208>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method BatchNormalization.call of <tensorflow.python.layers.normalization.BatchNormalization object at 0x7f82c30ac208>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BatchNormalization.call of <tensorflow.python.layers.normalization.BatchNormalization object at 0x7f82c30ac208>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Dropout.call of <tensorflow.python.layers.core.Dropout object at 0x7f82c30ac208>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dropout.call of <tensorflow.python.layers.core.Dropout object at 0x7f82c30ac208>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dropout.call of <tensorflow.python.layers.core.Dropout object at 0x7f82c30ac208>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dropout.call of <tensorflow.python.layers.core.Dropout object at 0x7f82c30ac208>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82af005f60>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82af005f60>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82af005f60>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82af005f60>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method BatchNormalization.call of <tensorflow.python.layers.normalization.BatchNormalization object at 0x7f82af005f60>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BatchNormalization.call of <tensorflow.python.layers.normalization.BatchNormalization object at 0x7f82af005f60>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method BatchNormalization.call of <tensorflow.python.layers.normalization.BatchNormalization object at 0x7f82af005f60>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BatchNormalization.call of <tensorflow.python.layers.normalization.BatchNormalization object at 0x7f82af005f60>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Dropout.call of <tensorflow.python.layers.core.Dropout object at 0x7f82af005f60>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dropout.call of <tensorflow.python.layers.core.Dropout object at 0x7f82af005f60>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dropout.call of <tensorflow.python.layers.core.Dropout object at 0x7f82af005f60>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dropout.call of <tensorflow.python.layers.core.Dropout object at 0x7f82af005f60>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82b4b8efd0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82b4b8efd0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82b4b8efd0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82b4b8efd0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method BatchNormalization.call of <tensorflow.python.layers.normalization.BatchNormalization object at 0x7f82aec96d68>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BatchNormalization.call of <tensorflow.python.layers.normalization.BatchNormalization object at 0x7f82aec96d68>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method BatchNormalization.call of <tensorflow.python.layers.normalization.BatchNormalization object at 0x7f82aec96d68>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BatchNormalization.call of <tensorflow.python.layers.normalization.BatchNormalization object at 0x7f82aec96d68>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Dropout.call of <tensorflow.python.layers.core.Dropout object at 0x7f82aec96d68>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dropout.call of <tensorflow.python.layers.core.Dropout object at 0x7f82aec96d68>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dropout.call of <tensorflow.python.layers.core.Dropout object at 0x7f82aec96d68>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dropout.call of <tensorflow.python.layers.core.Dropout object at 0x7f82aec96d68>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82ae8e69e8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82ae8e69e8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82ae8e69e8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82ae8e69e8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method BatchNormalization.call of <tensorflow.python.layers.normalization.BatchNormalization object at 0x7f82ae8e69e8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BatchNormalization.call of <tensorflow.python.layers.normalization.BatchNormalization object at 0x7f82ae8e69e8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method BatchNormalization.call of <tensorflow.python.layers.normalization.BatchNormalization object at 0x7f82ae8e69e8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method BatchNormalization.call of <tensorflow.python.layers.normalization.BatchNormalization object at 0x7f82ae8e69e8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82b4bef240>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82b4bef240>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82b4bef240>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f82b4bef240>>: AssertionError: Bad argument number for Name: 3, expecting 4\n"
     ]
    }
   ],
   "source": [
    "n_inputs = 28*28\n",
    "n_outputs = 5\n",
    "n_hidden_neurons = 100\n",
    "n_hidden_layers = 5\n",
    "\n",
    "reset_tf_graph()\n",
    "\n",
    "# 定义输入参数\n",
    "X = tf.placeholder(tf.float32, shape=(None, n_inputs), name=\"X\")\n",
    "y = tf.placeholder(tf.int32, shape=(None), name=\"y\")\n",
    "training = tf.placeholder(tf.bool, name=\"training\")\n",
    "\n",
    "# 定义层\n",
    "he_init = tf.initializers.variance_scaling()\n",
    "\n",
    "def make_dnn(inputs):\n",
    "    with tf.name_scope(\"dnn\") as scope:\n",
    "        for n in range(n_hidden_layers):\n",
    "            inputs = tf.layers.dropout(inputs, rate=0.5, training=training)\n",
    "            inputs = tf.layers.dense(inputs, n_hidden_neurons, \n",
    "                                     kernel_initializer=he_init,\n",
    "                                     name=\"hidden%d\" % (n + 1))\n",
    "            # 添加批量标准化\n",
    "            inputs = tf.nn.elu(tf.layers.batch_normalization(inputs, training=training, momentum=0.9))\n",
    "        return inputs\n",
    "\n",
    "dnn_outputs = make_dnn(X)\n",
    "logits = tf.layers.dense(dnn_outputs, n_outputs, \n",
    "                         kernel_initializer=he_init,\n",
    "                        name=\"logits\")\n",
    "y_probs = tf.nn.softmax(logits, name=\"y_probs\")\n",
    "\n",
    "# 定义交叉熵损失函数\n",
    "with tf.name_scope(\"loss\"):\n",
    "    xentropy = tf.nn.sparse_softmax_cross_entropy_with_logits(labels=y, logits=logits)\n",
    "    loss = tf.reduce_mean(xentropy, name=\"loss\")\n",
    "\n",
    "# 定义训练操作\n",
    "learning_rate = 0.01\n",
    "with tf.name_scope(\"train\"):\n",
    "    optimizer = tf.train.AdamOptimizer(learning_rate)\n",
    "    training_op = optimizer.minimize(loss)\n",
    "\n",
    "with tf.name_scope(\"eval\"):\n",
    "    correct = tf.nn.in_top_k(logits, y, 1)\n",
    "    accuracy = tf.reduce_mean(tf.cast(correct, tf.float32))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 61,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "0 loss:  0.24036792\n",
      "0 Validation accuracy: 0.92220485\n",
      "epoch: 0, validation loss: 0.240368, best loss: 0.240368, accuracy: 92.22%\n",
      "1 loss:  0.20601128\n",
      "1 Validation accuracy: 0.94018763\n",
      "epoch: 1, validation loss: 0.206011, best loss: 0.206011, accuracy: 94.02%\n",
      "2 loss:  0.19890918\n",
      "2 Validation accuracy: 0.94018763\n",
      "epoch: 2, validation loss: 0.198909, best loss: 0.198909, accuracy: 94.02%\n",
      "3 loss:  0.20729183\n",
      "3 Validation accuracy: 0.9413604\n",
      "epoch: 3, validation loss: 0.207292, best loss: 0.198909, accuracy: 94.14%\n",
      "4 loss:  0.16944982\n",
      "4 Validation accuracy: 0.9448788\n",
      "epoch: 4, validation loss: 0.169450, best loss: 0.169450, accuracy: 94.49%\n",
      "5 loss:  0.1524752\n",
      "5 Validation accuracy: 0.94917905\n",
      "epoch: 5, validation loss: 0.152475, best loss: 0.152475, accuracy: 94.92%\n",
      "6 loss:  0.16239944\n",
      "6 Validation accuracy: 0.95191556\n",
      "epoch: 6, validation loss: 0.162399, best loss: 0.152475, accuracy: 95.19%\n",
      "7 loss:  0.16008028\n",
      "7 Validation accuracy: 0.9526974\n",
      "epoch: 7, validation loss: 0.160080, best loss: 0.152475, accuracy: 95.27%\n",
      "8 loss:  0.13302137\n",
      "8 Validation accuracy: 0.9628616\n",
      "epoch: 8, validation loss: 0.133021, best loss: 0.133021, accuracy: 96.29%\n",
      "9 loss:  0.12288739\n",
      "9 Validation accuracy: 0.9644253\n",
      "epoch: 9, validation loss: 0.122887, best loss: 0.122887, accuracy: 96.44%\n",
      "10 loss:  0.13408995\n",
      "10 Validation accuracy: 0.9640344\n",
      "epoch: 10, validation loss: 0.134090, best loss: 0.122887, accuracy: 96.40%\n",
      "11 loss:  0.13429153\n",
      "11 Validation accuracy: 0.9628616\n",
      "epoch: 11, validation loss: 0.134292, best loss: 0.122887, accuracy: 96.29%\n",
      "12 loss:  0.12601388\n",
      "12 Validation accuracy: 0.9601251\n",
      "epoch: 12, validation loss: 0.126014, best loss: 0.122887, accuracy: 96.01%\n",
      "13 loss:  0.12335005\n",
      "13 Validation accuracy: 0.9640344\n",
      "epoch: 13, validation loss: 0.123350, best loss: 0.122887, accuracy: 96.40%\n",
      "14 loss:  0.13448156\n",
      "14 Validation accuracy: 0.96325254\n",
      "epoch: 14, validation loss: 0.134482, best loss: 0.122887, accuracy: 96.33%\n",
      "15 loss:  0.119753316\n",
      "15 Validation accuracy: 0.9644253\n",
      "epoch: 15, validation loss: 0.119753, best loss: 0.119753, accuracy: 96.44%\n",
      "16 loss:  0.11815361\n",
      "16 Validation accuracy: 0.9667709\n",
      "epoch: 16, validation loss: 0.118154, best loss: 0.118154, accuracy: 96.68%\n",
      "17 loss:  0.10472874\n",
      "17 Validation accuracy: 0.9702893\n",
      "epoch: 17, validation loss: 0.104729, best loss: 0.104729, accuracy: 97.03%\n",
      "18 loss:  0.1216771\n",
      "18 Validation accuracy: 0.9648163\n",
      "epoch: 18, validation loss: 0.121677, best loss: 0.104729, accuracy: 96.48%\n",
      "19 loss:  0.10262891\n",
      "19 Validation accuracy: 0.9710711\n",
      "epoch: 19, validation loss: 0.102629, best loss: 0.102629, accuracy: 97.11%\n",
      "20 loss:  0.113338575\n",
      "20 Validation accuracy: 0.9655981\n",
      "epoch: 20, validation loss: 0.113339, best loss: 0.102629, accuracy: 96.56%\n",
      "21 loss:  0.10716446\n",
      "21 Validation accuracy: 0.9683346\n",
      "epoch: 21, validation loss: 0.107164, best loss: 0.102629, accuracy: 96.83%\n",
      "22 loss:  0.10846707\n",
      "22 Validation accuracy: 0.9640344\n",
      "epoch: 22, validation loss: 0.108467, best loss: 0.102629, accuracy: 96.40%\n",
      "23 loss:  0.11066602\n",
      "23 Validation accuracy: 0.9683346\n",
      "epoch: 23, validation loss: 0.110666, best loss: 0.102629, accuracy: 96.83%\n",
      "24 loss:  0.122117855\n",
      "24 Validation accuracy: 0.96129787\n",
      "epoch: 24, validation loss: 0.122118, best loss: 0.102629, accuracy: 96.13%\n",
      "25 loss:  0.14851947\n",
      "25 Validation accuracy: 0.95308834\n",
      "epoch: 25, validation loss: 0.148519, best loss: 0.102629, accuracy: 95.31%\n",
      "26 loss:  0.13725826\n",
      "26 Validation accuracy: 0.96051604\n",
      "epoch: 26, validation loss: 0.137258, best loss: 0.102629, accuracy: 96.05%\n",
      "27 loss:  0.093550734\n",
      "27 Validation accuracy: 0.97263485\n",
      "epoch: 27, validation loss: 0.093551, best loss: 0.093551, accuracy: 97.26%\n",
      "28 loss:  0.11279164\n",
      "28 Validation accuracy: 0.9710711\n",
      "epoch: 28, validation loss: 0.112792, best loss: 0.093551, accuracy: 97.11%\n",
      "29 loss:  0.09739221\n",
      "29 Validation accuracy: 0.9691165\n",
      "epoch: 29, validation loss: 0.097392, best loss: 0.093551, accuracy: 96.91%\n",
      "30 loss:  0.10320319\n",
      "30 Validation accuracy: 0.97263485\n",
      "epoch: 30, validation loss: 0.103203, best loss: 0.093551, accuracy: 97.26%\n",
      "31 loss:  0.1035995\n",
      "31 Validation accuracy: 0.9675528\n",
      "epoch: 31, validation loss: 0.103600, best loss: 0.093551, accuracy: 96.76%\n",
      "32 loss:  0.10614923\n",
      "32 Validation accuracy: 0.9691165\n",
      "epoch: 32, validation loss: 0.106149, best loss: 0.093551, accuracy: 96.91%\n",
      "33 loss:  0.09736279\n",
      "33 Validation accuracy: 0.97224396\n",
      "epoch: 33, validation loss: 0.097363, best loss: 0.093551, accuracy: 97.22%\n",
      "34 loss:  0.10192355\n",
      "34 Validation accuracy: 0.97068024\n",
      "epoch: 34, validation loss: 0.101924, best loss: 0.093551, accuracy: 97.07%\n",
      "35 loss:  0.10389317\n",
      "35 Validation accuracy: 0.97341675\n",
      "epoch: 35, validation loss: 0.103893, best loss: 0.093551, accuracy: 97.34%\n",
      "36 loss:  0.10611153\n",
      "36 Validation accuracy: 0.96950746\n",
      "epoch: 36, validation loss: 0.106112, best loss: 0.093551, accuracy: 96.95%\n",
      "37 loss:  0.1071195\n",
      "37 Validation accuracy: 0.97068024\n",
      "epoch: 37, validation loss: 0.107120, best loss: 0.093551, accuracy: 97.07%\n",
      "38 loss:  0.1047798\n",
      "38 Validation accuracy: 0.97068024\n",
      "epoch: 38, validation loss: 0.104780, best loss: 0.093551, accuracy: 97.07%\n",
      "39 loss:  0.08352388\n",
      "39 Validation accuracy: 0.9741986\n",
      "epoch: 39, validation loss: 0.083524, best loss: 0.083524, accuracy: 97.42%\n",
      "40 loss:  0.11298199\n",
      "40 Validation accuracy: 0.9652072\n",
      "epoch: 40, validation loss: 0.112982, best loss: 0.083524, accuracy: 96.52%\n",
      "41 loss:  0.11437789\n",
      "41 Validation accuracy: 0.96325254\n",
      "epoch: 41, validation loss: 0.114378, best loss: 0.083524, accuracy: 96.33%\n",
      "42 loss:  0.10706816\n",
      "42 Validation accuracy: 0.96872556\n",
      "epoch: 42, validation loss: 0.107068, best loss: 0.083524, accuracy: 96.87%\n",
      "43 loss:  0.09486573\n",
      "43 Validation accuracy: 0.9741986\n",
      "epoch: 43, validation loss: 0.094866, best loss: 0.083524, accuracy: 97.42%\n",
      "44 loss:  0.08925726\n",
      "44 Validation accuracy: 0.9702893\n",
      "epoch: 44, validation loss: 0.089257, best loss: 0.083524, accuracy: 97.03%\n",
      "45 loss:  0.098407626\n",
      "45 Validation accuracy: 0.97068024\n",
      "epoch: 45, validation loss: 0.098408, best loss: 0.083524, accuracy: 97.07%\n",
      "46 loss:  0.101257086\n",
      "46 Validation accuracy: 0.9702893\n",
      "epoch: 46, validation loss: 0.101257, best loss: 0.083524, accuracy: 97.03%\n",
      "47 loss:  0.09547913\n",
      "47 Validation accuracy: 0.97380763\n",
      "epoch: 47, validation loss: 0.095479, best loss: 0.083524, accuracy: 97.38%\n",
      "48 loss:  0.11119111\n",
      "48 Validation accuracy: 0.9714621\n",
      "epoch: 48, validation loss: 0.111191, best loss: 0.083524, accuracy: 97.15%\n",
      "49 loss:  0.10342024\n",
      "49 Validation accuracy: 0.9714621\n",
      "epoch: 49, validation loss: 0.103420, best loss: 0.083524, accuracy: 97.15%\n",
      "50 loss:  0.09540993\n",
      "50 Validation accuracy: 0.97380763\n",
      "epoch: 50, validation loss: 0.095410, best loss: 0.083524, accuracy: 97.38%\n",
      "51 loss:  0.09748653\n",
      "51 Validation accuracy: 0.9710711\n",
      "epoch: 51, validation loss: 0.097487, best loss: 0.083524, accuracy: 97.11%\n",
      "52 loss:  0.10192611\n",
      "52 Validation accuracy: 0.9691165\n",
      "epoch: 52, validation loss: 0.101926, best loss: 0.083524, accuracy: 96.91%\n",
      "53 loss:  0.08493132\n",
      "53 Validation accuracy: 0.9745895\n",
      "epoch: 53, validation loss: 0.084931, best loss: 0.083524, accuracy: 97.46%\n",
      "54 loss:  0.10059873\n",
      "54 Validation accuracy: 0.9679437\n",
      "epoch: 54, validation loss: 0.100599, best loss: 0.083524, accuracy: 96.79%\n",
      "55 loss:  0.11735168\n",
      "55 Validation accuracy: 0.96598905\n",
      "epoch: 55, validation loss: 0.117352, best loss: 0.083524, accuracy: 96.60%\n",
      "56 loss:  0.10023453\n",
      "56 Validation accuracy: 0.96989834\n",
      "epoch: 56, validation loss: 0.100235, best loss: 0.083524, accuracy: 96.99%\n",
      "57 loss:  0.106176645\n",
      "57 Validation accuracy: 0.9683346\n",
      "epoch: 57, validation loss: 0.106177, best loss: 0.083524, accuracy: 96.83%\n",
      "58 loss:  0.10519632\n",
      "58 Validation accuracy: 0.97263485\n",
      "epoch: 58, validation loss: 0.105196, best loss: 0.083524, accuracy: 97.26%\n",
      "59 loss:  0.10803955\n",
      "59 Validation accuracy: 0.96989834\n",
      "epoch: 59, validation loss: 0.108040, best loss: 0.083524, accuracy: 96.99%\n",
      "60 loss:  0.09009535\n",
      "60 Validation accuracy: 0.9730258\n",
      "Early stopping! \n",
      "INFO:tensorflow:Restoring parameters from ./chpt11/model/ex8_4.ckpt\n",
      "Final test accuracy: 97.22%\n"
     ]
    }
   ],
   "source": [
    "n_epochs = 1000\n",
    "batch_size = 20\n",
    "n_epochs_before_stop = 20\n",
    "\n",
    "init = tf.global_variables_initializer()\n",
    "saver = tf.train.Saver()\n",
    "\n",
    "best_loss = np.infty\n",
    "\n",
    "\n",
    "# 定义一个从训练集中随机挑选50个实例的方法\n",
    "def batch_generator(X, y, size):\n",
    "    rnd_idx = np.random.permutation(len(X)) # len(X)是矩阵X的第0维的长度, 生成0..len(X)的随机数\n",
    "    n_batches = len(X) // batch_size # //是整除, mod\n",
    "    for batch_idx in np.array_split(rnd_idx, n_batches):\n",
    "        X_batch, y_batch = X[batch_idx], y[batch_idx]\n",
    "        yield X_batch, y_batch # yield定义了生成器generator, 可以用next(generator)来调用, 也可以用for循环调用\n",
    "        \n",
    "with tf.Session() as sess:\n",
    "    init.run()\n",
    "    n_epochs_after_best = 0\n",
    "    for epoch in range(n_epochs):\n",
    "        for X_batch, y_batch in batch_generator(X_train_04, y_train_04, batch_size):\n",
    "            sess.run(training_op, feed_dict={X: X_batch, y: y_batch, training: True})\n",
    "        \n",
    "        the_loss, acc_valid = sess.run([loss, accuracy], feed_dict={X: X_valid_04, y: y_valid_04, training: True})\n",
    "        print(epoch, \"loss: \", the_loss)\n",
    "        print(epoch, \"Validation accuracy:\", acc_valid)\n",
    "        \n",
    "        if the_loss < best_loss:\n",
    "            best_loss = the_loss\n",
    "            n_epochs_after_best = 0\n",
    "            save_path = saver.save(sess, \"./chpt11/model/ex8_4.ckpt\")\n",
    "        else:\n",
    "            n_epochs_after_best += 1\n",
    "            if n_epochs_after_best > n_epochs_before_stop:\n",
    "                print(\"Early stopping! \")\n",
    "                break\n",
    "        print(\"epoch: {}, validation loss: {:.6f}, best loss: {:.6f}, accuracy: {:.2f}%\".format(\n",
    "            epoch, the_loss, best_loss, acc_valid * 100))\n",
    "    \n",
    "with tf.Session() as sess:\n",
    "    saver.restore(sess, \"./chpt11/model/ex8_4.ckpt\")\n",
    "    acc_test = accuracy.eval(feed_dict={X: X_test_04, y: y_test_04, training: True})\n",
    "    print(\"Final test accuracy: {:.2f}%\".format(acc_test * 100))"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### "
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "dev-gpu",
   "language": "python",
   "name": "dev-gpu"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
